channels:
- conda-forge
dependencies:
- python=3.12.12
- pip
- pip:
  - mlflow==2.16.2
  - cloudpickle==3.1.2
  - colorama==0.4.6
  - numpy==1.26.4
  - pandas==2.3.3
  - pydot==4.0.1
  - torch==2.10.0
  - torchvision==0.25.0
  - tqdm==4.66.2
  - triton==3.6.0
name: mlflow-env
